### ISSUE TITLE
Paginas de autores

### ISSUE THREAD

**Issue by fandres69** [fandres69/Unad#8]
### Objetivos

Publicar información relacionada con los Autores del OVI.

### To Do

- [x] Será una (1) página web.

- [x] Se debe organizar un bloque por cada estudiante que participo en la actividad

**Se Debe publicar por cada estudiante**

- [x] Nombre.

- [x] Código.    

- [x] Programa.

- [x] Correo Electrónico.

- [x] Usuario Skype.

- [x] Fotografía reciente y real de cada estudiante.

**Comment by yonfis23** [comment]
Paginas de autores realizada
