### ISSUE TITLE
Requerimientos generales del OVI

### ISSUE THREAD

**Issue by fandres69** [fandres69/Unad#9]
## To Do

- [ ] El grupo deberá entregar el OVI completamente terminado y en estado 100% funcional así no participen todo los estudiantes o miembros del grupo colaborativo. 

- [x] El sitio web debe contar con un contador de visitas propio. 

- [x] El sitio web debe contar con un módulo o widget para la red social Twitter, donde se presenten los Feeds o Contenidos que se comparten en esta red social desde el perfil oficial de la universidad UNAD

**Comment by yonfis23** [comment]
Listo compañero ya cargue las paginas finales del proyecto
